version: "3.9"

services:
  worker:
    image: ghcr.io/chichocoria/worker:fa0fc9c
    env_file:
      - ./worker/.env
    depends_on:
      - database
      - redis
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - voting_app_network

  vote:
    image: ghcr.io/chichocoria/vote:fa0fc9c
    env_file:
      - ./vote/.env
    depends_on:
      - worker
    ports:
      - "80:80"
    restart: always
    networks:
      - voting_app_network

  result:
    image: ghcr.io/chichocoria/result:fa0fc9c
    env_file:
      - ./result/.env
    depends_on:
      - worker
    ports:
      - "3000:3000"
    restart: always
    networks:
      - voting_app_network

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - /var/lib/postgresql/data/stag:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - voting_app_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - voting_app_network

networks:
  voting_app_network: