name: Continuous Integration

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test-vote:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: desafio-semana-3/vote
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: pytest tests/

  test-result:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: desafio-semana-3/result
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  test-worker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: desafio-semana-3/worker
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f desafio-semana-3/docker-compose.yml up -d --build
      - run: curl -f http://localhost:80 || exit 1
      - run: curl -f http://localhost:3000 || exit 1
