name: Build and Push Docker Images with Tag

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🏷️ Set tag (short SHA)
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: 🔐 Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: 🐳 Build & Push vote
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/vote:${TAG} ./desafio-semana-3/vote
          docker push $REGISTRY/$IMAGE_OWNER/vote:${TAG}

      - name: 🐳 Build & Push result
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/result:${TAG} ./desafio-semana-3/result
          docker push $REGISTRY/$IMAGE_OWNER/result:${TAG}

      - name: 🐳 Build & Push worker
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/worker:${TAG} ./desafio-semana-3/worker
          docker push $REGISTRY/$IMAGE_OWNER/worker:${TAG}
