name: Build and Push Docker Images with Tag

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🏷️ Set tag (short SHA)
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: 🔐 Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: 🐳 Build & Push vote
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/vote:${TAG} ./desafio-semana-3/vote
          docker push $REGISTRY/$IMAGE_OWNER/vote:${TAG}

      - name: 🐳 Build & Push result
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/result:${TAG} ./desafio-semana-3/result
          docker push $REGISTRY/$IMAGE_OWNER/result:${TAG}

      - name: 🐳 Build & Push worker
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/worker:${TAG} ./desafio-semana-3/worker
          docker push $REGISTRY/$IMAGE_OWNER/worker:${TAG}
      
      - name: 🔁 Actualizar docker-compose.staging.yml con nuevo tag
        run: |
          sed -i "s|ghcr.io/${{ env.IMAGE_OWNER }}/vote:.*|ghcr.io/${{ env.IMAGE_OWNER }}/vote:${TAG}|g" desafio-semana-3/docker-compose.staging.yml
          sed -i "s|ghcr.io/${{ env.IMAGE_OWNER }}/result:.*|ghcr.io/${{ env.IMAGE_OWNER }}/result:${TAG}|g" desafio-semana-3/docker-compose.staging.yml
          sed -i "s|ghcr.io/${{ env.IMAGE_OWNER }}/worker:.*|ghcr.io/${{ env.IMAGE_OWNER }}/worker:${TAG}|g" desafio-semana-3/docker-compose.staging.yml

      - name: 🚀 Commit y push del docker-compose actualizado
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add desafio-semana-3/docker-compose.staging.yml
          git commit -m "🔁 Update docker-compose.staging.yml with tag ${TAG}" || echo "No changes to commit"
          git push