name: Health Check

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar salud
        run: |
          curl -f http://your-staging-url || exit 1
          curl -f http://your-production-url || exit 1