name: 🔁 Update docker-compose with new tag

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    branches:
      - develop
      - master
    types:
      - completed

jobs:
  update-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo en la rama correcta
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          persist-credentials: false

      - name: 🔖 Set tag SHA
        run: echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: ✍️ Reemplazar tags en docker-compose
        run: |
          if [ "${{ github.event.workflow_run.head_branch }}" == "develop" ]; then
            sed -i "s|ghcr.io/.*/vote:.*|ghcr.io/${{ github.repository_owner }}/vote:${TAG}|g" desafio-semana-3/docker-compose.staging.yml
            sed -i "s|ghcr.io/.*/result:.*|ghcr.io/${{ github.repository_owner }}/result:${TAG}|g" desafio-semana-3/docker-compose.staging.yml
            sed -i "s|ghcr.io/.*/worker:.*|ghcr.io/${{ github.repository_owner }}/worker:${TAG}|g" desafio-semana-3/docker-compose.staging.yml
          else
            sed -i "s|ghcr.io/.*/vote:.*|ghcr.io/${{ github.repository_owner }}/vote:${TAG}|g" desafio-semana-3/docker-compose.prod.yml
            sed -i "s|ghcr.io/.*/result:.*|ghcr.io/${{ github.repository_owner }}/result:${TAG}|g" desafio-semana-3/docker-compose.prod.yml
            sed -i "s|ghcr.io/.*/worker:.*|ghcr.io/${{ github.repository_owner }}/worker:${TAG}|g" desafio-semana-3/docker-compose.prod.yml
          fi

      - name: 💾 Commit y push del docker-compose actualizado
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if [ "${{ github.event.workflow_run.head_branch }}" == "develop" ]; then
            git add desafio-semana-3/docker-compose.staging.yml
          else
            git add desafio-semana-3/docker-compose.prod.yml
          fi
          git commit -m "🔁 Update docker-compose with tag ${TAG}" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git push origin ${{ github.event.workflow_run.head_branch }}
